---
title: "Dissertation Data Analysis"
output: html_document
date: "2024-02-07"
---

## Dissertation Data Analysis


```{r cars}
# Installing required packages 
install.packages("rstan")
install.packages("devtools")
devtools::install_github("GRousselet/rogme")
install.packages("brms")
install.packages('rstanarm')
install.packages('forestplot')
```

```{r}
# Loading required packages 
library(tidyr)
library(dplyr)
library(rstan)
library(devtools)
library(rogme)
library(brms)
library(rstanarm)
library(forestplot)
library(ggplot2)
library(cowplot)
library(knitr)
library(par)
library(rmeta)
```


```{r}
# Labelling my raw dataset
my_data <- X655080_240207_173339_long
```


```{r}
# Tidying up the dataset and selecting only the relevant columns 
## The only thing differentiating the face and car memory results was the column 'trialNo' was either numerical, or contained instructions. As such I told R to group 'correct' by learning the pattern of the 'trialNo' column. the file being removed is one that duplicated.

summarized_data <- my_data %>%
  filter(!is.na(filename) & filename != "" & filename != "655080_240109_153112_recovered.csv") %>%
  group_by(filename) %>%
  summarize(Gender = unique(gender),  
            Age = unique(age),  
            HoursSlept = unique(`Hours Slept Last Night`),  
            TotalEmpathy = sum(ifelse(!is.na(responseScore), responseScore, 0)),
            TotalFaceScore = sum(ifelse(grepl("^[0-9]+$", trialNo), correct, 0)),
            TotalCarScore = sum(ifelse(!grepl("^[0-9]+$", trialNo), correct, 0)))


```

```{r}
# Demographic graph for participant age and gender - summarized_data
age_groups <- cut(summarized_data$Age,
                  breaks = c(16, 18, 20, 25, 30, 40, 50, 60, Inf),
                  labels = c("16-18", "18-20", "20-25", "25-30", "30-40", "40-50", "50-60", "60+"))
age_gender_count <- table(age_groups, summarized_data$Gender)
age_gender_count_df <- as.data.frame.table(age_gender_count)
colnames(age_gender_count_df) <- c("Age_Group", "Gender", "Freq")

# Plotting
plot1 <- ggplot(age_gender_count_df, aes(x = Age_Group, y = Freq, fill = Gender)) +
  geom_bar(stat = "identity", position = "stack") +  # Stack bars on top of each other
  labs(title = "Original Participant Age Distrobution",
       x = "Age Group",
       y = "Number of Participants",
       fill = "Gender") +
  scale_fill_manual(values = c("blue", "orange", "darkred")) +  # Set color for each gender
  theme_minimal() +
  theme(
    text = element_text(size = 20),  
    axis.title = element_text(size = 26),  
    axis.text.x = element_text(angle = 45, hjust = 0.5)
  )


# Demographic graph for participant age and gender - final_empathy
final_empathy <- subset(final_empathy, Gender != "other")
age_groups2 <- cut(final_empathy$Age,
                   breaks = c(16, 18, 20, 25, 30, 40, 50, 60, Inf),
                   labels = c("16-18", "18-20", "20-25", "25-30", "30-40", "40-50", "50-60", "60+"))
age_gender_count2 <- table(age_groups2, final_empathy$Gender)
age_gender_count_df2 <- as.data.frame.table(age_gender_count2)
levels_df2 <- factor(age_gender_count_df2$Age_Group, levels = c("16-18", "18-20", "20-25", "25-30", "30-40", "40-50", "50-60", "60+"))
##fillng missing values with zeros 
age_gender_count_df2[is.na(age_gender_count_df2)] <- 0

# Plotting
plot2 <- ggplot(age_gender_count_df2, aes(x = age_groups2, y = Freq, fill = Var2)) +
  geom_bar(stat = "identity", position = "stack") +  # Stack bars on top of each other
  labs(title = "Subset Participant Age Distrobution",
       x = "Age Group",
       y = "Number of Participants",
       fill = "Gender") +
  scale_fill_manual(values = c("blue", "darkred")) +  # Set color for each gender
  theme_minimal() +
  theme(
    text = element_text(size = 20),  
    axis.title = element_text(size = 26),  
    axis.text.x = element_text(angle = 45, hjust = 0.5)
  )
plot2
YLIMDEMOG <- c(0, 60)

# Merging
merged_plot <- plot_grid(plot1 + ylim(YLIMDEMOG) + labs(tag = "A"), 
                         plot2 + ylim(YLIMDEMOG) + labs(tag = "B"), 
                         ncol = 2)
merged_plot
```


```{r}
# Age demographics
average_age <- mean(summarized_data$Age, na.rm = TRUE)
sd_age <- sd(summarized_data$Age, na.rm = TRUE)
range_age <- range(summarized_data$Age, na.rm = TRUE)
cat("Average Age:", round(average_age, 2), "\n")
cat("Standard Deviation of Age:", round(sd_age, 2), "\n")
cat("Range of Age:", range_age[1], "-", range_age[2], "\n")
```

```{r}
# Setting limits 
ylimit <- c(0, 72)
xlimit <- c(0, 80)
```

```{r}
# Superimposed box plots for group comparison 
## Only male and female for group comparison
filtered_data <- subset(summarized_data, Gender != "other")

## Gender differences in FM scores
plot_face <- ggplot(filtered_data, aes(x = Gender, y = TotalFaceScore)) +
  geom_boxplot(fill = "lightblue",  color = "darkred", alpha = 0.7) +
  geom_point(position = position_jitter(width = 0.2), color = "black", size = 2) +
  labs(title = "Gender Differences in CFMT Scores",
       x = "Gender",
       y = "CFMT Score") +
  theme_minimal() +
  theme(
    text = element_text(size = 26),  
    axis.title = element_text(size = 26),  
    axis.text = element_text(size = 26),
    plot.title = element_text(size = 26, hjust = 0.5)  
  ) +
  ylim(0, 72)  # Set the y-axis limits

## Gender differneces in CM scores
plot_car <- ggplot(filtered_data, aes(x = Gender, y = TotalCarScore)) +
  geom_boxplot(fill = "lightblue",  color = "darkred", alpha = 0.7) +
  geom_point(position = position_jitter(width = 0.2), color = "black", size = 2) +
  labs(title = "Gender Differences in CCMT Scores",
       x = "Gender",
       y = "CCMT Score") +
  theme_minimal() +
  theme(
    text = element_text(size = 26),  
    axis.title = element_text(size = 26),  
    axis.text = element_text(size = 26),
    plot.title = element_text(size = 26, hjust = 0.5)  
  ) +
  ylim(0, 72)  # Set the y-axis limits

# Combined plots
combined_plot <- plot_grid(plot_face, plot_car, labels = "AUTO", align = "hv", nrow = 1)
print(combined_plot)

```



```{r}
## Shift funciton
g1 <- summarized_data %>%
  filter(Gender == 'woman') %>%
  select(TotalFaceScore)

g2 <- summarized_data %>%
  filter(Gender == 'man') %>%
  select(TotalFaceScore)

df <- mkt2(g1, g2)

df <- unnest(df, obs)

ps <- plot_scat2(data = df,
                 formula = obs ~ gr,
                 xlabel = "Gender",
                 ylabel = "Distrobution of CFMT Scores",
                 alpha = 1,
                 shape = 21,
                 colour = "grey10",
                 fill = "grey90") #> scatterplots
ps <- ps + coord_flip()
ps
```


```{r}
#> compute shift function 
sf <- shifthd(data = df, formula = obs ~ gr, nboot = 200)
#> sf <- shifthd_pbci(data = df, formula = obs ~ gr, nboot = 200, q = c(.1,.25,.5,.75,.9))

#> plot shift function
psf <- plot_sf(sf, plot_theme = 2)
#> Warning: Using alpha for a discrete variable is not advised.

#> add labels for deciles 1 & 9
psf <- add_sf_lab(psf, sf, 
                  y_lab_nudge = .1, 
                  text_size = 6)

#> change axis labels
psf[[1]] <- psf[[1]] +  labs(x = "Group 1 quantiles of scores",
                             y = "Group 1 - group 2 \nquantile differences")
psf[[1]]
```

```{r}
#t-test
summarized_data <- subset(summarized_data, Gender != "other")
t_test_result <- t.test(TotalFaceScore ~ Gender, data = summarized_data)
t_test_result
```


```{r}
p <- plot_scat2(df,
                xlabel = "Gender",
                ylabel = "CFMT Scores",
                alpha = .3,
                shape = 21,
                colour = "grey10",
                fill = "grey90") #> scatterplots
p <- plot_hd_links(p, sf[[1]],
                    q_size = 1,
                    md_size = 1.5,
                    add_rect = TRUE,
                    rect_alpha = 0.1,
                    rect_col = "grey50",
                    add_lab = TRUE,
                    text_size = 5) #> superimposed deciles + rectangle
p <- p + coord_flip() #> flip axes
p
```


```{r}
# First plot - compute shift function
sf <- shifthd(data = df, formula = obs ~ gr, nboot = 200)
psf <- plot_sf(sf, plot_theme = 2)
psf <- add_sf_lab(psf, sf, y_lab_nudge = 0.1, text_size = 6)
psf[[1]] <- psf[[1]] + labs(x = "Group 1 quantiles of CFMT scores",
                            y = "Group 1 - group 2 \nquantile differences")

# Second plot - scatterplot
p <- plot_scat2(df,
                xlabel = "Gender \nGroup 1 = Female, Group 2 = Male",
                ylabel = "CFMT Scores",
                alpha = 0.3,
                shape = 21,
                colour = "grey10",
                fill = "grey90")
p <- plot_hd_links(p, sf[[1]],
                   q_size = 1,
                   md_size = 1.5,
                   add_rect = TRUE,
                   rect_alpha = 0.1,
                   rect_col = "grey50",
                   add_lab = TRUE,
                   text_size = 5)
p <- p + coord_flip()

# Combine the plots
combined_plot <- plot_grid(p, psf[[1]], labels = c("A", "B"), align = "h", nrow = 1)

# Print the combined plot
print(combined_plot)

```

```{r}
# T-test
summarized_data <- subset(summarized_data, Gender != "other")
t_test_result <- t.test(TotalFaceScore ~ Gender, data = summarized_data)


t_test_result
```



```{r}
# Removing participants who did not fully complete the EQ
final_empathy <- my_data %>%
  group_by(filename) %>%
  filter(!any(is.na(response))) %>%
  filter(filename != "" & filename != "655080_240109_153112_recovered.csv") %>%
  summarize(Gender = unique(gender),  
            Age = unique(age),  
            HoursSlept = unique(`Hours Slept Last Night`),  
            TotalEmpathy = sum(responseScore[!is.na(responseScore)]),
            TotalFaceScore = sum(ifelse(grepl("^[0-9]+$", trialNo), correct, 0)),
            TotalCarScore = sum(ifelse(!grepl("^[0-9]+$", trialNo), correct, 0)))
```



```{r}
# Descriptive stats for the second part of the analysis
num_men <- sum(final_empathy$Gender == "man")
print(num_men)
num_woman <- sum(final_empathy$Gender == "woman")
print(num_woman)
male_data <- final_empathy[final_empathy$Gender == "man", ]
female_data <- final_empathy[final_empathy$Gender == "woman", ]

# Calculate average empathy score
average_empathy_male <- mean(male_data$TotalEmpathy)
average_empathy_female <- mean(female_data$TotalEmpathy)

# Calculate standard deviation
sd_empathy_male <- sd(male_data$TotalEmpathy)
sd_empathy_female <- sd(female_data$TotalEmpathy)

```







```{r}
# First plot
plot1 <- ggplot(final_empathy, aes(x = TotalEmpathy, y = TotalFaceScore)) +
  geom_point(size = 2) + 
  geom_smooth(method = "lm", se = FALSE, color = "black") +  
  labs(title = "Relationship between EQ and CFMT Score", x = "EQ Score", y = "CFMT Score") +
  theme(
    text = element_text(size = 16),  
    axis.title = element_text(size = 16), 
    axis.text = element_text(size = 16),
    plot.title = element_text(size = 20, hjust = 0.5))  +
  ylim(ylimit) +  # Set y-axis limits
  xlim(xlimit)

# Second plot
plot2 <- ggplot(final_empathy, aes(x = TotalEmpathy, y = TotalCarScore)) +
  geom_point(size = 2) + 
  geom_smooth(method = "lm", se = FALSE, color = "black") +  
  labs(title = "Relationship between EQ and CCMT Score", x = "EQ Score", y = "CCMT Score") +
  theme(
    text = element_text(size = 16),  
    axis.title = element_text(size = 16), 
    axis.text = element_text(size = 16),
    plot.title = element_text(size = 20, hjust = 0.5))  +
  ylim(ylimit) +  # Set y-axis limits
  xlim(xlimit)

# Third plot
plot3 <- ggplot(final_empathy, aes(x = TotalCarScore, y = TotalFaceScore)) +
  geom_point(size = 2) +  
  geom_smooth(method = "lm", se = FALSE, color = "black") +  
  labs(title = "Relationship between CFMT and CCMT Scores", x = "CCMT Score", y = "CFMT Score") +
  theme(
    text = element_text(size = 16),  
    axis.title = element_text(size = 16), 
    axis.text = element_text(size = 16),
    plot.title = element_text(size = 20, hjust = 0.5)) +
  ylim(xlimit2) +  # Set y-axis limits
  xlim(xlimit2)

# Fourth plot
plot4 <- ggplot(final_empathy, aes(x = TotalEmpathy, y = TotalFaceScore, color = Gender)) +
  geom_point(size = 2, aes(shape = Gender)) +  
  geom_smooth(data = data_men, method = "lm", se = FALSE, color = "blue") +  
  geom_smooth(data = data_women, method = "lm", se = FALSE, color = "darkred") +  
  scale_color_manual(values = c("man" = "blue", "woman" = "darkred")) +  
  scale_shape_manual(values = c("man" = 16, "woman" = 17)) + 
  labs(title = "        Relationship Between EQ and CFMT Scores by Gender", x = "EQ Score", y = "CFMT Score") +
  theme(
    text = element_text(size = 16),  
    axis.title = element_text(size = 16), 
    axis.text = element_text(size = 16),
    plot.title = element_text(size = 20, hjust = 0.5)
  ) +
  ylim(ylimit) +  # Set y-axis limits
  xlim(xlimit)    # Set x-axis limits

# Combining plots
combined_plot <- plot_grid(plot1, plot2, plot3, plot4, labels = c("A", "B", "C", "D"), align = "hv", ncol = 2)
print(combined_plot)

```



```{r}
# Running regression

brms_data <- final_empathy

# Removing other gender from the new dataset
brms_data <- subset(brms_data, Gender != "other")

# Recode 'woman' to 0 and 'man' to 1
brms_data$Gender <- ifelse(brms_data$Gender == "woman", 0, 
                            ifelse(brms_data$Gender == "man", 1, brms_data$Gender))

# Calculating the mean of TotalEmpathy and TotalCarScore
mean_TotalEmpathy <- mean(brms_data$TotalEmpathy)
mean_TotalCarScore <- mean(brms_data$TotalCarScore)

# Centering the TotalEmpathy and TotalCarScore predictors
brms_data$TotalEmpathy_centered <- brms_data$TotalEmpathy - mean_TotalEmpathy
brms_data$TotalCarScore_centered <- brms_data$TotalCarScore - mean_TotalCarScore

# Converting Gender to numeric
brms_data$Gender <- as.numeric(as.character(brms_data$Gender))

mean_Gender <- mean(brms_data$Gender)
# Center the Gender predictor
brms_data$Gender_centered <- brms_data$Gender - mean_Gender



# Fitting the brms model with centered predictors
model <- brm(
  formula = TotalFaceScore ~  TotalEmpathy_centered + TotalCarScore_centered,
  data = brms_data,
  control = list(max_treedepth = 15), 
  iter = 4000, 
  warmup = 2000 
)

print(model)
```


```{r}
# Stan glm model from textbook - Displaying uncertainty in the fitted regression
fit_2 <- stan_glm(TotalFaceScore ~ TotalEmpathy, data = final_empathy)


sims_2 <- as.matrix(fit_2)
n_sims_2 <- nrow(sims_2)
beta_hat_2 <- apply(sims_2, 2, median)


plot(final_empathy$TotalEmpathy, final_empathy$TotalFaceScore, xlab = "EQ Score", ylab = "CFMT Score")
sims_display <- sample(n_sims_2, 10)
for (i in sims_display) {
  abline(sims_2[i, 1], sims_2[i, 2], col = "gray")
}
abline(coef(fit_2)[1], coef(fit_2)[2], col = "black")


```



```{r}
# Calculate Hedges' g
calculate_hedges_g <- function(mean1, mean2, sd1, sd2, n1, n2) {
  pooled_sd <- sqrt(((n1 - 1) * sd1^2 + (n2 - 1) * sd2^2) / (n1 + n2 - 2))
  hedges_g <- (mean1 - mean2) / pooled_sd * (1 - (3 / (4 * (n1 + n2) - 9)))
  return(hedges_g)
}

# Sub in data here
mean_male <- 53.07
mean_female <-56.28
sd_male <- 11.46
sd_female <- 10.64
n_male <- 93
n_female <- 26


# Final Calculation
finalhedges_g <- calculate_hedges_g(mean_male, mean_female, sd_male, sd_female, n_male, n_female)
cat("Hedges' g:", finalhedges_g, "\n")

print(finalhedges_g)

```

```{r}
# Calculate confidence intervals for Hedges' g
calculate_ci_hedges_g_female_superiority <- function(mean1, mean2, sd1, sd2, n1, n2, alpha = 0.05) {
  g <- -calculate_hedges_g(mean1, mean2, sd1, sd2, n1, n2)
  pooled_sd <- sqrt(((n1 - 1) * sd1^2 + (n2 - 1) * sd2^2) / (n1 + n2 - 2))
  SE_g <- sqrt(((n1 + n2) / (n1 * n2)) + (g^2 / (2 * (n1 + n2))))
  df <- n1 + n2 - 2
  t_value <- qt(1 - alpha / 2, df)
  lower_limit <- g - t_value * SE_g
  upper_limit <- g + t_value * SE_g
  return(c(lower_limit, upper_limit))
}

# Given data
mean_male <- 53.07
mean_female <-56.28
sd_male <- 11.46
sd_female <- 10.64
n_male <- 93
n_female <- 26

# Calculate confidence intervals for Hedges' g
ci_hedges_g_female_superiority <- calculate_ci_hedges_g_female_superiority(mean_male, mean_female, sd_male, sd_female, n_male, n_female)
cat("Lower limit (Female superiority):", ci_hedges_g_female_superiority[1], "\n")
cat("Upper limit (Female superiority):", ci_hedges_g_female_superiority[2], "\n")


```

`


```{r}
# Forestplot

base_data <- tibble::tibble(
  HedgesD = c(0.31, 0.28, 0.04, 0.31, 0.28, 0.34, 0.26, 0.21),
  lower = c(-0.24, -0.15, -0.28, 0.04, 0.03, 0.08, 0.02, 0.11),
  upper = c(0.84, 0.72, 0.37, 0.57, 0.54, 0.6, 0.5, 0.32),
  Total_Participants = c(50, 121, 153, 227, 251, 289, 343, 1435), 
  study = c(
    "Duchaine & Nakayama, (2006) [n = 50]", "Present Study, (2024) [n = 121]", "Dennett et al., (2011) [n = 153] ",
    "McGugin et al., (2012) [n = 227]", "Bobak et al., (2016) [n = 251]", "Bowles et al., (2009) [n = 289]",
    "Østergaard et al., (2021) [n = 343]", "Peterson & Leue, (2021) [n = 1435]")
)

base_data <- base_data %>%
  arrange(Total_Participants)

forestplot(
  labeltext = base_data$study,
  mean = base_data$HedgesD,
  lower = base_data$lower,
  upper = base_data$upper,
  clip = c(-1, 1),
  xlab = "Hedges' g",
  txt_gp = fpTxtGp(
    xlab = gpar(cex = 2),  # Increase font size for X axis label
    ticks = gpar(cex = 1.5),  # Increase font size for X axis ticks
    label = gpar(cex = 2)  # Increase font size for Y axis labels
  ),
  lwd.ci = 5  # Adjust line width for confidence intervals
)
```








